name: Demo Workflow

on: 
  workflow_call:
    inputs:
      santosh:
        required: false
        default: dev
        type: string


  push:
    branches:
    - main
    - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

# env:
#   MY_VAR: Hi there! This workflow running from 
#   MNAME: environment
#   managedby: SantoshJi
  


jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
 
    - name: Print a greeting
      run: |
        echo ${{ inputs.santosh }}
        
