name: Demo Workflow

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
 
    - name: Print a greeting
      run: echo "Hello World, this is my first workflow from Github Actions"

    - name: List Files
      run: ls -l

    - name: Read Readme.md
      run: cat README.md
  
  secondjob:
    name: second job
    runs-on: ubuntu-latest
    needs: firstjob
    if: always()
    steps:
    - name: List Files
      run: ls -l

    - name: Read Readme.md
      run: cat README.md
    
      
    
