name: Demo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: select the environment
        default: dev
        type: string
  # push:
  #   branches:
  #   - main
  #   - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

  
jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Environment name is ${{ inputs.environment }}"
