name: Demo Workflow

on: 
  workflow_dispatch:
    inputs:
      santosh:
        default: dev
        type: string
  # push:
  #   branches:
  #   - main
  #   - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

  
jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/demo.yaml
      with:
        santosh: qa
    - name: Print a greeting
      run: echo ${{ inputs.santosh }}
