name: Demo Workflow

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

env:
  MY_VAR: Hi there! This workflow running from 
  NAME: dev
  MNAME: environment
  managedby: SantoshJi


jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
 
    - name: Print a greeting
      run: |
        echo '$MY_VAR $NAME $MNAME, Thanks to $managedby !'
