name: Demo Workflow

on: 
  workflow_call:
    inputs:
      santosh:
        description: Select environment
        required: true
        default: dev
        type: string


  push:
    branches:
    - main
    - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**

env:
  MY_VAR: Hi there! This workflow running from 
  MNAME: environment
  managedby: SantoshJi
  


jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
 
    - name: Print a greeting
      run: |
        echo $MY_VAR - ${{ inputs.santosh }} - $MNAME, Thanks to $managedby !
        
