name: application demo workflow

on:
 push:
   branches:
   - main
   - feature/**

 pull_request:
   branches:
   -  main
   

jobs:
  demo: 
    name: Demo job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Gretting 
      run: echo "hello word"

    - name: list file
      run: ls -l

    - name: read file
      run: cat package.json
