name: Application DemoWork Flow

on: workflow_dispatch

jobs:
  demo:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
    - name: Greetings
      run: echo "Hello World"
      
    - name: list files
      run: ls -l

    - name: read file
      run: cat package.json

